  - platform: template
    sensors:
      car_fully_charged_time:
        value_template: >-
          {% if is_state('switch.wvwxxxxxxxxxxxx_charging', 'on') %}
            {% set charging_time_left_str = states('sensor.wvwxxxxxxxxxxxx_charging_time_left') %}
            {% set charging_time_left = charging_time_left_str.split(',')[0] | int(default=0) %}
            {% set last_connected_time_str = states('sensor.wvwxxxxxxxxxxxx_last_connected') %}
            
            {% if last_connected_time_str %}
              {% set last_connected_time = strptime(last_connected_time_str, '%Y-%m-%d %H:%M:%S') %}
            {% else %}
              {% set last_connected_time = now() %}
            {% endif %}

            {% if charging_time_left != 0 %}
              {% set fully_charged_time = last_connected_time + timedelta(minutes=charging_time_left) %}
              The car will be charged in: {{ "%02d:%02d" | format(fully_charged_time.hour, fully_charged_time.minute) }}
            {% else %}
              No data
            {% endif %}
          {% else %}
            No charging
          {% endif %}
          
        friendly_name: 'Time when Car will be Fully Charged'
        icon_template: mdi:car-electric
